export function PlatformDisclaimer() {
  return (
    <div className="mt-12 pt-6 border-t" data-testid="platform-disclaimer">
      <p className="text-xs text-muted-foreground leading-relaxed">
        By using the Tableicity Platform ("Platform"), you acknowledge and agree that the information, data, and documents generated by the Platform are provided for general informational purposes only and may not be appropriate for your particular circumstances. You should always consult with qualified legal, financial, or tax professionals before making decisions based on content produced by the Platform. You release and hold harmless Tableicity and its affiliates from any liability, claims, or damages arising from your use of the Platform. Please review our{" "}
        <a href="/terms" className="underline hover:text-foreground transition-colors" data-testid="link-terms">
          Terms of Service
        </a>{" "}
        and{" "}
        <a href="/privacy" className="underline hover:text-foreground transition-colors" data-testid="link-privacy">
          Privacy Policy
        </a>
        .
      </p>
    </div>
  );
}
